### PR TITLE
Beautify readme.md with some emojis

### PR DESCRIPTION
**Pull request by speedyman09**
Lmk if anything should be changed

### CODE REVIEW

**Review by jvyden — CHANGES_REQUESTED** [review]
I think it's *okay* for the headers, but putting them mid-paragraph is a little much.

I probably won't merge this either way since emojis in repositories' readmes have always felt wrong to me, but I'd like to see what others think

**Comment by speedyman09** [comment]
@turecross321 what is your opinion on this?

**Comment by turecross321** [comment]
I think it looks a bit tacky with emojis mid-paragraph too, but I like them in headers.
That being said, I think more than one emoji per header is too much, and it might be worth experimenting with putting the emoji before the text as opposed to after it.

**Comment by jvyden** [comment]
I mostly agree with Ture. By the way, we should probably use the actual Unicode characters - most markdown parsers don't support shortcodes.

**Comment by speedyman09** [comment]
Can you explain a usecase where someone would be using a custom markdown parser?

**Comment by jvyden** [comment]
image

**Pull request merged**
